# mypy: ignore-errors
# Generated by the Protocol Buffers compiler. DO NOT EDIT!
# source: machine/machine.proto
# plugin: grpclib.plugin.main
import abc
import typing

import grpclib.const
import grpclib.client
if typing.TYPE_CHECKING:
    import grpclib.server

from . import common_pb2
import google.protobuf.any_pb2
import google.protobuf.duration_pb2
import google.protobuf.empty_pb2
import google.protobuf.timestamp_pb2
from . import machine_pb2


class MachineServiceBase(abc.ABC):

    @abc.abstractmethod
    async def ApplyConfiguration(self, stream: 'grpclib.server.Stream[machine_pb2.ApplyConfigurationRequest, machine_pb2.ApplyConfigurationResponse]') -> None:
        pass

    @abc.abstractmethod
    async def Bootstrap(self, stream: 'grpclib.server.Stream[machine_pb2.BootstrapRequest, machine_pb2.BootstrapResponse]') -> None:
        pass

    @abc.abstractmethod
    async def Containers(self, stream: 'grpclib.server.Stream[machine_pb2.ContainersRequest, machine_pb2.ContainersResponse]') -> None:
        pass

    @abc.abstractmethod
    async def Copy(self, stream: 'grpclib.server.Stream[machine_pb2.CopyRequest, common_pb2.Data]') -> None:
        pass

    @abc.abstractmethod
    async def CPUFreqStats(self, stream: 'grpclib.server.Stream[google.protobuf.empty_pb2.Empty, machine_pb2.CPUFreqStatsResponse]') -> None:
        pass

    @abc.abstractmethod
    async def CPUInfo(self, stream: 'grpclib.server.Stream[google.protobuf.empty_pb2.Empty, machine_pb2.CPUInfoResponse]') -> None:
        pass

    @abc.abstractmethod
    async def DiskStats(self, stream: 'grpclib.server.Stream[google.protobuf.empty_pb2.Empty, machine_pb2.DiskStatsResponse]') -> None:
        pass

    @abc.abstractmethod
    async def Dmesg(self, stream: 'grpclib.server.Stream[machine_pb2.DmesgRequest, common_pb2.Data]') -> None:
        pass

    @abc.abstractmethod
    async def Events(self, stream: 'grpclib.server.Stream[machine_pb2.EventsRequest, machine_pb2.Event]') -> None:
        pass

    @abc.abstractmethod
    async def EtcdMemberList(self, stream: 'grpclib.server.Stream[machine_pb2.EtcdMemberListRequest, machine_pb2.EtcdMemberListResponse]') -> None:
        pass

    @abc.abstractmethod
    async def EtcdRemoveMemberByID(self, stream: 'grpclib.server.Stream[machine_pb2.EtcdRemoveMemberByIDRequest, machine_pb2.EtcdRemoveMemberByIDResponse]') -> None:
        pass

    @abc.abstractmethod
    async def EtcdLeaveCluster(self, stream: 'grpclib.server.Stream[machine_pb2.EtcdLeaveClusterRequest, machine_pb2.EtcdLeaveClusterResponse]') -> None:
        pass

    @abc.abstractmethod
    async def EtcdForfeitLeadership(self, stream: 'grpclib.server.Stream[machine_pb2.EtcdForfeitLeadershipRequest, machine_pb2.EtcdForfeitLeadershipResponse]') -> None:
        pass

    @abc.abstractmethod
    async def EtcdRecover(self, stream: 'grpclib.server.Stream[common_pb2.Data, machine_pb2.EtcdRecoverResponse]') -> None:
        pass

    @abc.abstractmethod
    async def EtcdSnapshot(self, stream: 'grpclib.server.Stream[machine_pb2.EtcdSnapshotRequest, common_pb2.Data]') -> None:
        pass

    @abc.abstractmethod
    async def EtcdAlarmList(self, stream: 'grpclib.server.Stream[google.protobuf.empty_pb2.Empty, machine_pb2.EtcdAlarmListResponse]') -> None:
        pass

    @abc.abstractmethod
    async def EtcdAlarmDisarm(self, stream: 'grpclib.server.Stream[google.protobuf.empty_pb2.Empty, machine_pb2.EtcdAlarmDisarmResponse]') -> None:
        pass

    @abc.abstractmethod
    async def EtcdDefragment(self, stream: 'grpclib.server.Stream[google.protobuf.empty_pb2.Empty, machine_pb2.EtcdDefragmentResponse]') -> None:
        pass

    @abc.abstractmethod
    async def EtcdStatus(self, stream: 'grpclib.server.Stream[google.protobuf.empty_pb2.Empty, machine_pb2.EtcdStatusResponse]') -> None:
        pass

    @abc.abstractmethod
    async def EtcdDowngradeValidate(self, stream: 'grpclib.server.Stream[machine_pb2.EtcdDowngradeValidateRequest, machine_pb2.EtcdDowngradeValidateResponse]') -> None:
        pass

    @abc.abstractmethod
    async def EtcdDowngradeEnable(self, stream: 'grpclib.server.Stream[machine_pb2.EtcdDowngradeEnableRequest, machine_pb2.EtcdDowngradeEnableResponse]') -> None:
        pass

    @abc.abstractmethod
    async def EtcdDowngradeCancel(self, stream: 'grpclib.server.Stream[google.protobuf.empty_pb2.Empty, machine_pb2.EtcdDowngradeCancelResponse]') -> None:
        pass

    @abc.abstractmethod
    async def Hostname(self, stream: 'grpclib.server.Stream[google.protobuf.empty_pb2.Empty, machine_pb2.HostnameResponse]') -> None:
        pass

    @abc.abstractmethod
    async def Kubeconfig(self, stream: 'grpclib.server.Stream[google.protobuf.empty_pb2.Empty, common_pb2.Data]') -> None:
        pass

    @abc.abstractmethod
    async def List(self, stream: 'grpclib.server.Stream[machine_pb2.ListRequest, machine_pb2.FileInfo]') -> None:
        pass

    @abc.abstractmethod
    async def DiskUsage(self, stream: 'grpclib.server.Stream[machine_pb2.DiskUsageRequest, machine_pb2.DiskUsageInfo]') -> None:
        pass

    @abc.abstractmethod
    async def LoadAvg(self, stream: 'grpclib.server.Stream[google.protobuf.empty_pb2.Empty, machine_pb2.LoadAvgResponse]') -> None:
        pass

    @abc.abstractmethod
    async def Logs(self, stream: 'grpclib.server.Stream[machine_pb2.LogsRequest, common_pb2.Data]') -> None:
        pass

    @abc.abstractmethod
    async def LogsContainers(self, stream: 'grpclib.server.Stream[google.protobuf.empty_pb2.Empty, machine_pb2.LogsContainersResponse]') -> None:
        pass

    @abc.abstractmethod
    async def Memory(self, stream: 'grpclib.server.Stream[google.protobuf.empty_pb2.Empty, machine_pb2.MemoryResponse]') -> None:
        pass

    @abc.abstractmethod
    async def Mounts(self, stream: 'grpclib.server.Stream[google.protobuf.empty_pb2.Empty, machine_pb2.MountsResponse]') -> None:
        pass

    @abc.abstractmethod
    async def NetworkDeviceStats(self, stream: 'grpclib.server.Stream[google.protobuf.empty_pb2.Empty, machine_pb2.NetworkDeviceStatsResponse]') -> None:
        pass

    @abc.abstractmethod
    async def Processes(self, stream: 'grpclib.server.Stream[google.protobuf.empty_pb2.Empty, machine_pb2.ProcessesResponse]') -> None:
        pass

    @abc.abstractmethod
    async def Read(self, stream: 'grpclib.server.Stream[machine_pb2.ReadRequest, common_pb2.Data]') -> None:
        pass

    @abc.abstractmethod
    async def Reboot(self, stream: 'grpclib.server.Stream[machine_pb2.RebootRequest, machine_pb2.RebootResponse]') -> None:
        pass

    @abc.abstractmethod
    async def Restart(self, stream: 'grpclib.server.Stream[machine_pb2.RestartRequest, machine_pb2.RestartResponse]') -> None:
        pass

    @abc.abstractmethod
    async def Rollback(self, stream: 'grpclib.server.Stream[machine_pb2.RollbackRequest, machine_pb2.RollbackResponse]') -> None:
        pass

    @abc.abstractmethod
    async def Reset(self, stream: 'grpclib.server.Stream[machine_pb2.ResetRequest, machine_pb2.ResetResponse]') -> None:
        pass

    @abc.abstractmethod
    async def ServiceList(self, stream: 'grpclib.server.Stream[google.protobuf.empty_pb2.Empty, machine_pb2.ServiceListResponse]') -> None:
        pass

    @abc.abstractmethod
    async def ServiceRestart(self, stream: 'grpclib.server.Stream[machine_pb2.ServiceRestartRequest, machine_pb2.ServiceRestartResponse]') -> None:
        pass

    @abc.abstractmethod
    async def ServiceStart(self, stream: 'grpclib.server.Stream[machine_pb2.ServiceStartRequest, machine_pb2.ServiceStartResponse]') -> None:
        pass

    @abc.abstractmethod
    async def ServiceStop(self, stream: 'grpclib.server.Stream[machine_pb2.ServiceStopRequest, machine_pb2.ServiceStopResponse]') -> None:
        pass

    @abc.abstractmethod
    async def Shutdown(self, stream: 'grpclib.server.Stream[machine_pb2.ShutdownRequest, machine_pb2.ShutdownResponse]') -> None:
        pass

    @abc.abstractmethod
    async def Stats(self, stream: 'grpclib.server.Stream[machine_pb2.StatsRequest, machine_pb2.StatsResponse]') -> None:
        pass

    @abc.abstractmethod
    async def SystemStat(self, stream: 'grpclib.server.Stream[google.protobuf.empty_pb2.Empty, machine_pb2.SystemStatResponse]') -> None:
        pass

    @abc.abstractmethod
    async def Upgrade(self, stream: 'grpclib.server.Stream[machine_pb2.UpgradeRequest, machine_pb2.UpgradeResponse]') -> None:
        pass

    @abc.abstractmethod
    async def Version(self, stream: 'grpclib.server.Stream[google.protobuf.empty_pb2.Empty, machine_pb2.VersionResponse]') -> None:
        pass

    @abc.abstractmethod
    async def GenerateClientConfiguration(self, stream: 'grpclib.server.Stream[machine_pb2.GenerateClientConfigurationRequest, machine_pb2.GenerateClientConfigurationResponse]') -> None:
        pass

    @abc.abstractmethod
    async def PacketCapture(self, stream: 'grpclib.server.Stream[machine_pb2.PacketCaptureRequest, common_pb2.Data]') -> None:
        pass

    @abc.abstractmethod
    async def Netstat(self, stream: 'grpclib.server.Stream[machine_pb2.NetstatRequest, machine_pb2.NetstatResponse]') -> None:
        pass

    @abc.abstractmethod
    async def MetaWrite(self, stream: 'grpclib.server.Stream[machine_pb2.MetaWriteRequest, machine_pb2.MetaWriteResponse]') -> None:
        pass

    @abc.abstractmethod
    async def MetaDelete(self, stream: 'grpclib.server.Stream[machine_pb2.MetaDeleteRequest, machine_pb2.MetaDeleteResponse]') -> None:
        pass

    @abc.abstractmethod
    async def ImageList(self, stream: 'grpclib.server.Stream[machine_pb2.ImageListRequest, machine_pb2.ImageListResponse]') -> None:
        pass

    @abc.abstractmethod
    async def ImagePull(self, stream: 'grpclib.server.Stream[machine_pb2.ImagePullRequest, machine_pb2.ImagePullResponse]') -> None:
        pass

    def __mapping__(self) -> typing.Dict[str, grpclib.const.Handler]:
        return {
            '/machine.MachineService/ApplyConfiguration': grpclib.const.Handler(
                self.ApplyConfiguration,
                grpclib.const.Cardinality.UNARY_UNARY,
                machine_pb2.ApplyConfigurationRequest,
                machine_pb2.ApplyConfigurationResponse,
            ),
            '/machine.MachineService/Bootstrap': grpclib.const.Handler(
                self.Bootstrap,
                grpclib.const.Cardinality.UNARY_UNARY,
                machine_pb2.BootstrapRequest,
                machine_pb2.BootstrapResponse,
            ),
            '/machine.MachineService/Containers': grpclib.const.Handler(
                self.Containers,
                grpclib.const.Cardinality.UNARY_UNARY,
                machine_pb2.ContainersRequest,
                machine_pb2.ContainersResponse,
            ),
            '/machine.MachineService/Copy': grpclib.const.Handler(
                self.Copy,
                grpclib.const.Cardinality.UNARY_STREAM,
                machine_pb2.CopyRequest,
                common_pb2.Data,
            ),
            '/machine.MachineService/CPUFreqStats': grpclib.const.Handler(
                self.CPUFreqStats,
                grpclib.const.Cardinality.UNARY_UNARY,
                google.protobuf.empty_pb2.Empty,
                machine_pb2.CPUFreqStatsResponse,
            ),
            '/machine.MachineService/CPUInfo': grpclib.const.Handler(
                self.CPUInfo,
                grpclib.const.Cardinality.UNARY_UNARY,
                google.protobuf.empty_pb2.Empty,
                machine_pb2.CPUInfoResponse,
            ),
            '/machine.MachineService/DiskStats': grpclib.const.Handler(
                self.DiskStats,
                grpclib.const.Cardinality.UNARY_UNARY,
                google.protobuf.empty_pb2.Empty,
                machine_pb2.DiskStatsResponse,
            ),
            '/machine.MachineService/Dmesg': grpclib.const.Handler(
                self.Dmesg,
                grpclib.const.Cardinality.UNARY_STREAM,
                machine_pb2.DmesgRequest,
                common_pb2.Data,
            ),
            '/machine.MachineService/Events': grpclib.const.Handler(
                self.Events,
                grpclib.const.Cardinality.UNARY_STREAM,
                machine_pb2.EventsRequest,
                machine_pb2.Event,
            ),
            '/machine.MachineService/EtcdMemberList': grpclib.const.Handler(
                self.EtcdMemberList,
                grpclib.const.Cardinality.UNARY_UNARY,
                machine_pb2.EtcdMemberListRequest,
                machine_pb2.EtcdMemberListResponse,
            ),
            '/machine.MachineService/EtcdRemoveMemberByID': grpclib.const.Handler(
                self.EtcdRemoveMemberByID,
                grpclib.const.Cardinality.UNARY_UNARY,
                machine_pb2.EtcdRemoveMemberByIDRequest,
                machine_pb2.EtcdRemoveMemberByIDResponse,
            ),
            '/machine.MachineService/EtcdLeaveCluster': grpclib.const.Handler(
                self.EtcdLeaveCluster,
                grpclib.const.Cardinality.UNARY_UNARY,
                machine_pb2.EtcdLeaveClusterRequest,
                machine_pb2.EtcdLeaveClusterResponse,
            ),
            '/machine.MachineService/EtcdForfeitLeadership': grpclib.const.Handler(
                self.EtcdForfeitLeadership,
                grpclib.const.Cardinality.UNARY_UNARY,
                machine_pb2.EtcdForfeitLeadershipRequest,
                machine_pb2.EtcdForfeitLeadershipResponse,
            ),
            '/machine.MachineService/EtcdRecover': grpclib.const.Handler(
                self.EtcdRecover,
                grpclib.const.Cardinality.STREAM_UNARY,
                common_pb2.Data,
                machine_pb2.EtcdRecoverResponse,
            ),
            '/machine.MachineService/EtcdSnapshot': grpclib.const.Handler(
                self.EtcdSnapshot,
                grpclib.const.Cardinality.UNARY_STREAM,
                machine_pb2.EtcdSnapshotRequest,
                common_pb2.Data,
            ),
            '/machine.MachineService/EtcdAlarmList': grpclib.const.Handler(
                self.EtcdAlarmList,
                grpclib.const.Cardinality.UNARY_UNARY,
                google.protobuf.empty_pb2.Empty,
                machine_pb2.EtcdAlarmListResponse,
            ),
            '/machine.MachineService/EtcdAlarmDisarm': grpclib.const.Handler(
                self.EtcdAlarmDisarm,
                grpclib.const.Cardinality.UNARY_UNARY,
                google.protobuf.empty_pb2.Empty,
                machine_pb2.EtcdAlarmDisarmResponse,
            ),
            '/machine.MachineService/EtcdDefragment': grpclib.const.Handler(
                self.EtcdDefragment,
                grpclib.const.Cardinality.UNARY_UNARY,
                google.protobuf.empty_pb2.Empty,
                machine_pb2.EtcdDefragmentResponse,
            ),
            '/machine.MachineService/EtcdStatus': grpclib.const.Handler(
                self.EtcdStatus,
                grpclib.const.Cardinality.UNARY_UNARY,
                google.protobuf.empty_pb2.Empty,
                machine_pb2.EtcdStatusResponse,
            ),
            '/machine.MachineService/EtcdDowngradeValidate': grpclib.const.Handler(
                self.EtcdDowngradeValidate,
                grpclib.const.Cardinality.UNARY_UNARY,
                machine_pb2.EtcdDowngradeValidateRequest,
                machine_pb2.EtcdDowngradeValidateResponse,
            ),
            '/machine.MachineService/EtcdDowngradeEnable': grpclib.const.Handler(
                self.EtcdDowngradeEnable,
                grpclib.const.Cardinality.UNARY_UNARY,
                machine_pb2.EtcdDowngradeEnableRequest,
                machine_pb2.EtcdDowngradeEnableResponse,
            ),
            '/machine.MachineService/EtcdDowngradeCancel': grpclib.const.Handler(
                self.EtcdDowngradeCancel,
                grpclib.const.Cardinality.UNARY_UNARY,
                google.protobuf.empty_pb2.Empty,
                machine_pb2.EtcdDowngradeCancelResponse,
            ),
            '/machine.MachineService/Hostname': grpclib.const.Handler(
                self.Hostname,
                grpclib.const.Cardinality.UNARY_UNARY,
                google.protobuf.empty_pb2.Empty,
                machine_pb2.HostnameResponse,
            ),
            '/machine.MachineService/Kubeconfig': grpclib.const.Handler(
                self.Kubeconfig,
                grpclib.const.Cardinality.UNARY_STREAM,
                google.protobuf.empty_pb2.Empty,
                common_pb2.Data,
            ),
            '/machine.MachineService/List': grpclib.const.Handler(
                self.List,
                grpclib.const.Cardinality.UNARY_STREAM,
                machine_pb2.ListRequest,
                machine_pb2.FileInfo,
            ),
            '/machine.MachineService/DiskUsage': grpclib.const.Handler(
                self.DiskUsage,
                grpclib.const.Cardinality.UNARY_STREAM,
                machine_pb2.DiskUsageRequest,
                machine_pb2.DiskUsageInfo,
            ),
            '/machine.MachineService/LoadAvg': grpclib.const.Handler(
                self.LoadAvg,
                grpclib.const.Cardinality.UNARY_UNARY,
                google.protobuf.empty_pb2.Empty,
                machine_pb2.LoadAvgResponse,
            ),
            '/machine.MachineService/Logs': grpclib.const.Handler(
                self.Logs,
                grpclib.const.Cardinality.UNARY_STREAM,
                machine_pb2.LogsRequest,
                common_pb2.Data,
            ),
            '/machine.MachineService/LogsContainers': grpclib.const.Handler(
                self.LogsContainers,
                grpclib.const.Cardinality.UNARY_UNARY,
                google.protobuf.empty_pb2.Empty,
                machine_pb2.LogsContainersResponse,
            ),
            '/machine.MachineService/Memory': grpclib.const.Handler(
                self.Memory,
                grpclib.const.Cardinality.UNARY_UNARY,
                google.protobuf.empty_pb2.Empty,
                machine_pb2.MemoryResponse,
            ),
            '/machine.MachineService/Mounts': grpclib.const.Handler(
                self.Mounts,
                grpclib.const.Cardinality.UNARY_UNARY,
                google.protobuf.empty_pb2.Empty,
                machine_pb2.MountsResponse,
            ),
            '/machine.MachineService/NetworkDeviceStats': grpclib.const.Handler(
                self.NetworkDeviceStats,
                grpclib.const.Cardinality.UNARY_UNARY,
                google.protobuf.empty_pb2.Empty,
                machine_pb2.NetworkDeviceStatsResponse,
            ),
            '/machine.MachineService/Processes': grpclib.const.Handler(
                self.Processes,
                grpclib.const.Cardinality.UNARY_UNARY,
                google.protobuf.empty_pb2.Empty,
                machine_pb2.ProcessesResponse,
            ),
            '/machine.MachineService/Read': grpclib.const.Handler(
                self.Read,
                grpclib.const.Cardinality.UNARY_STREAM,
                machine_pb2.ReadRequest,
                common_pb2.Data,
            ),
            '/machine.MachineService/Reboot': grpclib.const.Handler(
                self.Reboot,
                grpclib.const.Cardinality.UNARY_UNARY,
                machine_pb2.RebootRequest,
                machine_pb2.RebootResponse,
            ),
            '/machine.MachineService/Restart': grpclib.const.Handler(
                self.Restart,
                grpclib.const.Cardinality.UNARY_UNARY,
                machine_pb2.RestartRequest,
                machine_pb2.RestartResponse,
            ),
            '/machine.MachineService/Rollback': grpclib.const.Handler(
                self.Rollback,
                grpclib.const.Cardinality.UNARY_UNARY,
                machine_pb2.RollbackRequest,
                machine_pb2.RollbackResponse,
            ),
            '/machine.MachineService/Reset': grpclib.const.Handler(
                self.Reset,
                grpclib.const.Cardinality.UNARY_UNARY,
                machine_pb2.ResetRequest,
                machine_pb2.ResetResponse,
            ),
            '/machine.MachineService/ServiceList': grpclib.const.Handler(
                self.ServiceList,
                grpclib.const.Cardinality.UNARY_UNARY,
                google.protobuf.empty_pb2.Empty,
                machine_pb2.ServiceListResponse,
            ),
            '/machine.MachineService/ServiceRestart': grpclib.const.Handler(
                self.ServiceRestart,
                grpclib.const.Cardinality.UNARY_UNARY,
                machine_pb2.ServiceRestartRequest,
                machine_pb2.ServiceRestartResponse,
            ),
            '/machine.MachineService/ServiceStart': grpclib.const.Handler(
                self.ServiceStart,
                grpclib.const.Cardinality.UNARY_UNARY,
                machine_pb2.ServiceStartRequest,
                machine_pb2.ServiceStartResponse,
            ),
            '/machine.MachineService/ServiceStop': grpclib.const.Handler(
                self.ServiceStop,
                grpclib.const.Cardinality.UNARY_UNARY,
                machine_pb2.ServiceStopRequest,
                machine_pb2.ServiceStopResponse,
            ),
            '/machine.MachineService/Shutdown': grpclib.const.Handler(
                self.Shutdown,
                grpclib.const.Cardinality.UNARY_UNARY,
                machine_pb2.ShutdownRequest,
                machine_pb2.ShutdownResponse,
            ),
            '/machine.MachineService/Stats': grpclib.const.Handler(
                self.Stats,
                grpclib.const.Cardinality.UNARY_UNARY,
                machine_pb2.StatsRequest,
                machine_pb2.StatsResponse,
            ),
            '/machine.MachineService/SystemStat': grpclib.const.Handler(
                self.SystemStat,
                grpclib.const.Cardinality.UNARY_UNARY,
                google.protobuf.empty_pb2.Empty,
                machine_pb2.SystemStatResponse,
            ),
            '/machine.MachineService/Upgrade': grpclib.const.Handler(
                self.Upgrade,
                grpclib.const.Cardinality.UNARY_UNARY,
                machine_pb2.UpgradeRequest,
                machine_pb2.UpgradeResponse,
            ),
            '/machine.MachineService/Version': grpclib.const.Handler(
                self.Version,
                grpclib.const.Cardinality.UNARY_UNARY,
                google.protobuf.empty_pb2.Empty,
                machine_pb2.VersionResponse,
            ),
            '/machine.MachineService/GenerateClientConfiguration': grpclib.const.Handler(
                self.GenerateClientConfiguration,
                grpclib.const.Cardinality.UNARY_UNARY,
                machine_pb2.GenerateClientConfigurationRequest,
                machine_pb2.GenerateClientConfigurationResponse,
            ),
            '/machine.MachineService/PacketCapture': grpclib.const.Handler(
                self.PacketCapture,
                grpclib.const.Cardinality.UNARY_STREAM,
                machine_pb2.PacketCaptureRequest,
                common_pb2.Data,
            ),
            '/machine.MachineService/Netstat': grpclib.const.Handler(
                self.Netstat,
                grpclib.const.Cardinality.UNARY_UNARY,
                machine_pb2.NetstatRequest,
                machine_pb2.NetstatResponse,
            ),
            '/machine.MachineService/MetaWrite': grpclib.const.Handler(
                self.MetaWrite,
                grpclib.const.Cardinality.UNARY_UNARY,
                machine_pb2.MetaWriteRequest,
                machine_pb2.MetaWriteResponse,
            ),
            '/machine.MachineService/MetaDelete': grpclib.const.Handler(
                self.MetaDelete,
                grpclib.const.Cardinality.UNARY_UNARY,
                machine_pb2.MetaDeleteRequest,
                machine_pb2.MetaDeleteResponse,
            ),
            '/machine.MachineService/ImageList': grpclib.const.Handler(
                self.ImageList,
                grpclib.const.Cardinality.UNARY_STREAM,
                machine_pb2.ImageListRequest,
                machine_pb2.ImageListResponse,
            ),
            '/machine.MachineService/ImagePull': grpclib.const.Handler(
                self.ImagePull,
                grpclib.const.Cardinality.UNARY_UNARY,
                machine_pb2.ImagePullRequest,
                machine_pb2.ImagePullResponse,
            ),
        }


class MachineServiceStub:

    def __init__(self, channel: grpclib.client.Channel) -> None:
        self.ApplyConfiguration = grpclib.client.UnaryUnaryMethod(
            channel,
            '/machine.MachineService/ApplyConfiguration',
            machine_pb2.ApplyConfigurationRequest,
            machine_pb2.ApplyConfigurationResponse,
        )
        self.Bootstrap = grpclib.client.UnaryUnaryMethod(
            channel,
            '/machine.MachineService/Bootstrap',
            machine_pb2.BootstrapRequest,
            machine_pb2.BootstrapResponse,
        )
        self.Containers = grpclib.client.UnaryUnaryMethod(
            channel,
            '/machine.MachineService/Containers',
            machine_pb2.ContainersRequest,
            machine_pb2.ContainersResponse,
        )
        self.Copy = grpclib.client.UnaryStreamMethod(
            channel,
            '/machine.MachineService/Copy',
            machine_pb2.CopyRequest,
            common_pb2.Data,
        )
        self.CPUFreqStats = grpclib.client.UnaryUnaryMethod(
            channel,
            '/machine.MachineService/CPUFreqStats',
            google.protobuf.empty_pb2.Empty,
            machine_pb2.CPUFreqStatsResponse,
        )
        self.CPUInfo = grpclib.client.UnaryUnaryMethod(
            channel,
            '/machine.MachineService/CPUInfo',
            google.protobuf.empty_pb2.Empty,
            machine_pb2.CPUInfoResponse,
        )
        self.DiskStats = grpclib.client.UnaryUnaryMethod(
            channel,
            '/machine.MachineService/DiskStats',
            google.protobuf.empty_pb2.Empty,
            machine_pb2.DiskStatsResponse,
        )
        self.Dmesg = grpclib.client.UnaryStreamMethod(
            channel,
            '/machine.MachineService/Dmesg',
            machine_pb2.DmesgRequest,
            common_pb2.Data,
        )
        self.Events = grpclib.client.UnaryStreamMethod(
            channel,
            '/machine.MachineService/Events',
            machine_pb2.EventsRequest,
            machine_pb2.Event,
        )
        self.EtcdMemberList = grpclib.client.UnaryUnaryMethod(
            channel,
            '/machine.MachineService/EtcdMemberList',
            machine_pb2.EtcdMemberListRequest,
            machine_pb2.EtcdMemberListResponse,
        )
        self.EtcdRemoveMemberByID = grpclib.client.UnaryUnaryMethod(
            channel,
            '/machine.MachineService/EtcdRemoveMemberByID',
            machine_pb2.EtcdRemoveMemberByIDRequest,
            machine_pb2.EtcdRemoveMemberByIDResponse,
        )
        self.EtcdLeaveCluster = grpclib.client.UnaryUnaryMethod(
            channel,
            '/machine.MachineService/EtcdLeaveCluster',
            machine_pb2.EtcdLeaveClusterRequest,
            machine_pb2.EtcdLeaveClusterResponse,
        )
        self.EtcdForfeitLeadership = grpclib.client.UnaryUnaryMethod(
            channel,
            '/machine.MachineService/EtcdForfeitLeadership',
            machine_pb2.EtcdForfeitLeadershipRequest,
            machine_pb2.EtcdForfeitLeadershipResponse,
        )
        self.EtcdRecover = grpclib.client.StreamUnaryMethod(
            channel,
            '/machine.MachineService/EtcdRecover',
            common_pb2.Data,
            machine_pb2.EtcdRecoverResponse,
        )
        self.EtcdSnapshot = grpclib.client.UnaryStreamMethod(
            channel,
            '/machine.MachineService/EtcdSnapshot',
            machine_pb2.EtcdSnapshotRequest,
            common_pb2.Data,
        )
        self.EtcdAlarmList = grpclib.client.UnaryUnaryMethod(
            channel,
            '/machine.MachineService/EtcdAlarmList',
            google.protobuf.empty_pb2.Empty,
            machine_pb2.EtcdAlarmListResponse,
        )
        self.EtcdAlarmDisarm = grpclib.client.UnaryUnaryMethod(
            channel,
            '/machine.MachineService/EtcdAlarmDisarm',
            google.protobuf.empty_pb2.Empty,
            machine_pb2.EtcdAlarmDisarmResponse,
        )
        self.EtcdDefragment = grpclib.client.UnaryUnaryMethod(
            channel,
            '/machine.MachineService/EtcdDefragment',
            google.protobuf.empty_pb2.Empty,
            machine_pb2.EtcdDefragmentResponse,
        )
        self.EtcdStatus = grpclib.client.UnaryUnaryMethod(
            channel,
            '/machine.MachineService/EtcdStatus',
            google.protobuf.empty_pb2.Empty,
            machine_pb2.EtcdStatusResponse,
        )
        self.EtcdDowngradeValidate = grpclib.client.UnaryUnaryMethod(
            channel,
            '/machine.MachineService/EtcdDowngradeValidate',
            machine_pb2.EtcdDowngradeValidateRequest,
            machine_pb2.EtcdDowngradeValidateResponse,
        )
        self.EtcdDowngradeEnable = grpclib.client.UnaryUnaryMethod(
            channel,
            '/machine.MachineService/EtcdDowngradeEnable',
            machine_pb2.EtcdDowngradeEnableRequest,
            machine_pb2.EtcdDowngradeEnableResponse,
        )
        self.EtcdDowngradeCancel = grpclib.client.UnaryUnaryMethod(
            channel,
            '/machine.MachineService/EtcdDowngradeCancel',
            google.protobuf.empty_pb2.Empty,
            machine_pb2.EtcdDowngradeCancelResponse,
        )
        self.Hostname = grpclib.client.UnaryUnaryMethod(
            channel,
            '/machine.MachineService/Hostname',
            google.protobuf.empty_pb2.Empty,
            machine_pb2.HostnameResponse,
        )
        self.Kubeconfig = grpclib.client.UnaryStreamMethod(
            channel,
            '/machine.MachineService/Kubeconfig',
            google.protobuf.empty_pb2.Empty,
            common_pb2.Data,
        )
        self.List = grpclib.client.UnaryStreamMethod(
            channel,
            '/machine.MachineService/List',
            machine_pb2.ListRequest,
            machine_pb2.FileInfo,
        )
        self.DiskUsage = grpclib.client.UnaryStreamMethod(
            channel,
            '/machine.MachineService/DiskUsage',
            machine_pb2.DiskUsageRequest,
            machine_pb2.DiskUsageInfo,
        )
        self.LoadAvg = grpclib.client.UnaryUnaryMethod(
            channel,
            '/machine.MachineService/LoadAvg',
            google.protobuf.empty_pb2.Empty,
            machine_pb2.LoadAvgResponse,
        )
        self.Logs = grpclib.client.UnaryStreamMethod(
            channel,
            '/machine.MachineService/Logs',
            machine_pb2.LogsRequest,
            common_pb2.Data,
        )
        self.LogsContainers = grpclib.client.UnaryUnaryMethod(
            channel,
            '/machine.MachineService/LogsContainers',
            google.protobuf.empty_pb2.Empty,
            machine_pb2.LogsContainersResponse,
        )
        self.Memory = grpclib.client.UnaryUnaryMethod(
            channel,
            '/machine.MachineService/Memory',
            google.protobuf.empty_pb2.Empty,
            machine_pb2.MemoryResponse,
        )
        self.Mounts = grpclib.client.UnaryUnaryMethod(
            channel,
            '/machine.MachineService/Mounts',
            google.protobuf.empty_pb2.Empty,
            machine_pb2.MountsResponse,
        )
        self.NetworkDeviceStats = grpclib.client.UnaryUnaryMethod(
            channel,
            '/machine.MachineService/NetworkDeviceStats',
            google.protobuf.empty_pb2.Empty,
            machine_pb2.NetworkDeviceStatsResponse,
        )
        self.Processes = grpclib.client.UnaryUnaryMethod(
            channel,
            '/machine.MachineService/Processes',
            google.protobuf.empty_pb2.Empty,
            machine_pb2.ProcessesResponse,
        )
        self.Read = grpclib.client.UnaryStreamMethod(
            channel,
            '/machine.MachineService/Read',
            machine_pb2.ReadRequest,
            common_pb2.Data,
        )
        self.Reboot = grpclib.client.UnaryUnaryMethod(
            channel,
            '/machine.MachineService/Reboot',
            machine_pb2.RebootRequest,
            machine_pb2.RebootResponse,
        )
        self.Restart = grpclib.client.UnaryUnaryMethod(
            channel,
            '/machine.MachineService/Restart',
            machine_pb2.RestartRequest,
            machine_pb2.RestartResponse,
        )
        self.Rollback = grpclib.client.UnaryUnaryMethod(
            channel,
            '/machine.MachineService/Rollback',
            machine_pb2.RollbackRequest,
            machine_pb2.RollbackResponse,
        )
        self.Reset = grpclib.client.UnaryUnaryMethod(
            channel,
            '/machine.MachineService/Reset',
            machine_pb2.ResetRequest,
            machine_pb2.ResetResponse,
        )
        self.ServiceList = grpclib.client.UnaryUnaryMethod(
            channel,
            '/machine.MachineService/ServiceList',
            google.protobuf.empty_pb2.Empty,
            machine_pb2.ServiceListResponse,
        )
        self.ServiceRestart = grpclib.client.UnaryUnaryMethod(
            channel,
            '/machine.MachineService/ServiceRestart',
            machine_pb2.ServiceRestartRequest,
            machine_pb2.ServiceRestartResponse,
        )
        self.ServiceStart = grpclib.client.UnaryUnaryMethod(
            channel,
            '/machine.MachineService/ServiceStart',
            machine_pb2.ServiceStartRequest,
            machine_pb2.ServiceStartResponse,
        )
        self.ServiceStop = grpclib.client.UnaryUnaryMethod(
            channel,
            '/machine.MachineService/ServiceStop',
            machine_pb2.ServiceStopRequest,
            machine_pb2.ServiceStopResponse,
        )
        self.Shutdown = grpclib.client.UnaryUnaryMethod(
            channel,
            '/machine.MachineService/Shutdown',
            machine_pb2.ShutdownRequest,
            machine_pb2.ShutdownResponse,
        )
        self.Stats = grpclib.client.UnaryUnaryMethod(
            channel,
            '/machine.MachineService/Stats',
            machine_pb2.StatsRequest,
            machine_pb2.StatsResponse,
        )
        self.SystemStat = grpclib.client.UnaryUnaryMethod(
            channel,
            '/machine.MachineService/SystemStat',
            google.protobuf.empty_pb2.Empty,
            machine_pb2.SystemStatResponse,
        )
        self.Upgrade = grpclib.client.UnaryUnaryMethod(
            channel,
            '/machine.MachineService/Upgrade',
            machine_pb2.UpgradeRequest,
            machine_pb2.UpgradeResponse,
        )
        self.Version = grpclib.client.UnaryUnaryMethod(
            channel,
            '/machine.MachineService/Version',
            google.protobuf.empty_pb2.Empty,
            machine_pb2.VersionResponse,
        )
        self.GenerateClientConfiguration = grpclib.client.UnaryUnaryMethod(
            channel,
            '/machine.MachineService/GenerateClientConfiguration',
            machine_pb2.GenerateClientConfigurationRequest,
            machine_pb2.GenerateClientConfigurationResponse,
        )
        self.PacketCapture = grpclib.client.UnaryStreamMethod(
            channel,
            '/machine.MachineService/PacketCapture',
            machine_pb2.PacketCaptureRequest,
            common_pb2.Data,
        )
        self.Netstat = grpclib.client.UnaryUnaryMethod(
            channel,
            '/machine.MachineService/Netstat',
            machine_pb2.NetstatRequest,
            machine_pb2.NetstatResponse,
        )
        self.MetaWrite = grpclib.client.UnaryUnaryMethod(
            channel,
            '/machine.MachineService/MetaWrite',
            machine_pb2.MetaWriteRequest,
            machine_pb2.MetaWriteResponse,
        )
        self.MetaDelete = grpclib.client.UnaryUnaryMethod(
            channel,
            '/machine.MachineService/MetaDelete',
            machine_pb2.MetaDeleteRequest,
            machine_pb2.MetaDeleteResponse,
        )
        self.ImageList = grpclib.client.UnaryStreamMethod(
            channel,
            '/machine.MachineService/ImageList',
            machine_pb2.ImageListRequest,
            machine_pb2.ImageListResponse,
        )
        self.ImagePull = grpclib.client.UnaryUnaryMethod(
            channel,
            '/machine.MachineService/ImagePull',
            machine_pb2.ImagePullRequest,
            machine_pb2.ImagePullResponse,
        )
