# mypy: ignore-errors
# Generated by the Protocol Buffers compiler. DO NOT EDIT!
# source: v1alpha1/state.proto
# plugin: grpclib.plugin.main
import abc
import typing

import grpclib.const
import grpclib.client
if typing.TYPE_CHECKING:
    import grpclib.server

from . import resource_pb2
from . import state_pb2


class StateBase(abc.ABC):

    @abc.abstractmethod
    async def Get(self, stream: 'grpclib.server.Stream[state_pb2.GetRequest, state_pb2.GetResponse]') -> None:
        pass

    @abc.abstractmethod
    async def List(self, stream: 'grpclib.server.Stream[state_pb2.ListRequest, state_pb2.ListResponse]') -> None:
        pass

    @abc.abstractmethod
    async def Create(self, stream: 'grpclib.server.Stream[state_pb2.CreateRequest, state_pb2.CreateResponse]') -> None:
        pass

    @abc.abstractmethod
    async def Update(self, stream: 'grpclib.server.Stream[state_pb2.UpdateRequest, state_pb2.UpdateResponse]') -> None:
        pass

    @abc.abstractmethod
    async def Destroy(self, stream: 'grpclib.server.Stream[state_pb2.DestroyRequest, state_pb2.DestroyResponse]') -> None:
        pass

    @abc.abstractmethod
    async def Watch(self, stream: 'grpclib.server.Stream[state_pb2.WatchRequest, state_pb2.WatchResponse]') -> None:
        pass

    def __mapping__(self) -> typing.Dict[str, grpclib.const.Handler]:
        return {
            '/cosi.resource.State/Get': grpclib.const.Handler(
                self.Get,
                grpclib.const.Cardinality.UNARY_UNARY,
                state_pb2.GetRequest,
                state_pb2.GetResponse,
            ),
            '/cosi.resource.State/List': grpclib.const.Handler(
                self.List,
                grpclib.const.Cardinality.UNARY_STREAM,
                state_pb2.ListRequest,
                state_pb2.ListResponse,
            ),
            '/cosi.resource.State/Create': grpclib.const.Handler(
                self.Create,
                grpclib.const.Cardinality.UNARY_UNARY,
                state_pb2.CreateRequest,
                state_pb2.CreateResponse,
            ),
            '/cosi.resource.State/Update': grpclib.const.Handler(
                self.Update,
                grpclib.const.Cardinality.UNARY_UNARY,
                state_pb2.UpdateRequest,
                state_pb2.UpdateResponse,
            ),
            '/cosi.resource.State/Destroy': grpclib.const.Handler(
                self.Destroy,
                grpclib.const.Cardinality.UNARY_UNARY,
                state_pb2.DestroyRequest,
                state_pb2.DestroyResponse,
            ),
            '/cosi.resource.State/Watch': grpclib.const.Handler(
                self.Watch,
                grpclib.const.Cardinality.UNARY_STREAM,
                state_pb2.WatchRequest,
                state_pb2.WatchResponse,
            ),
        }


class StateStub:

    def __init__(self, channel: grpclib.client.Channel) -> None:
        self.Get = grpclib.client.UnaryUnaryMethod(
            channel,
            '/cosi.resource.State/Get',
            state_pb2.GetRequest,
            state_pb2.GetResponse,
        )
        self.List = grpclib.client.UnaryStreamMethod(
            channel,
            '/cosi.resource.State/List',
            state_pb2.ListRequest,
            state_pb2.ListResponse,
        )
        self.Create = grpclib.client.UnaryUnaryMethod(
            channel,
            '/cosi.resource.State/Create',
            state_pb2.CreateRequest,
            state_pb2.CreateResponse,
        )
        self.Update = grpclib.client.UnaryUnaryMethod(
            channel,
            '/cosi.resource.State/Update',
            state_pb2.UpdateRequest,
            state_pb2.UpdateResponse,
        )
        self.Destroy = grpclib.client.UnaryUnaryMethod(
            channel,
            '/cosi.resource.State/Destroy',
            state_pb2.DestroyRequest,
            state_pb2.DestroyResponse,
        )
        self.Watch = grpclib.client.UnaryStreamMethod(
            channel,
            '/cosi.resource.State/Watch',
            state_pb2.WatchRequest,
            state_pb2.WatchResponse,
        )
