#!/usr/bin/env bash
#
# Regenerate the vendored Python gRPC stubs under
# custom_components/talos_linux/proto/ from upstream proto sources.
#
# Usage:
#   scripts/generate_proto.sh [TALOS_TAG]
#
# TALOS_TAG defaults to v1.13.5. The matching cosi-project/runtime version is
# read from the Talos tag's go.mod, so bumping the Talos pin is a one-arg change.
#
# The generated files are committed; do NOT hand-edit them. Re-run this script
# when the pin changes.
#
set -euo pipefail

TALOS_TAG="${1:-v1.13.5}"
# Pinned so the generated *_pb2.py carry protobuf gencode 6.31.1. Home Assistant
# ships protobuf runtime 6.32.0; protobuf refuses to load stubs whose gencode is
# newer than the runtime, so the gencode must stay <= what HA ships. Do not bump
# this to a grpcio-tools release that raises the protobuf floor above HA's.
GRPCIO_TOOLS_VERSION="1.80.0"
# Service stubs are generated by grpclib's protoc plugin (protoc-gen-python_grpc,
# flag --python_grpc_out). grpcio's BoringSSL can't do Ed25519 mTLS, which Talos
# PKI requires; grpclib runs on Python's ssl module, which can.
GRPCLIB_VERSION="0.4.9"

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
PKG_DIR="$REPO_ROOT/custom_components/talos_linux"
OUT_DIR="$PKG_DIR/proto"
VENV_DIR="$REPO_ROOT/.venv"
PY="$VENV_DIR/bin/python"

echo ">> Talos tag: $TALOS_TAG"

# --- toolchain -------------------------------------------------------------
if [ ! -x "$PY" ]; then
  echo ">> Creating venv at $VENV_DIR"
  python3 -m venv "$VENV_DIR"
fi
"$PY" -m pip install -q --disable-pip-version-check \
  "grpcio-tools==${GRPCIO_TOOLS_VERSION}" "grpclib[protobuf]==${GRPCLIB_VERSION}" \
  googleapis-common-protos

# protoc discovers the grpclib plugin (protoc-gen-python_grpc) on PATH; grpclib
# installs it into the venv's bin dir.
export PATH="$VENV_DIR/bin:$PATH"

GRPC_INC="$("$PY" -c 'import grpc_tools, os; print(os.path.join(os.path.dirname(grpc_tools.__file__), "_proto"))')"

# --- scratch workspace -----------------------------------------------------
WORK="$(mktemp -d)"
cleanup() { rm -rf "$WORK"; }
trap cleanup EXIT

# --- fetch Talos protos ----------------------------------------------------
echo ">> Cloning siderolabs/talos @ $TALOS_TAG"
git clone --quiet --depth 1 --branch "$TALOS_TAG" \
  https://github.com/siderolabs/talos "$WORK/talos"

# cosi-project/runtime version is whatever this Talos tag pins.
COSI_VER="$(grep -E 'github.com/cosi-project/runtime ' "$WORK/talos/go.mod" \
  | head -1 | awk '{print $2}')"
if [ -z "$COSI_VER" ]; then
  echo "!! Could not read cosi-project/runtime version from go.mod" >&2
  exit 1
fi
echo ">> cosi-project/runtime: $COSI_VER (from Talos go.mod)"
echo ">> Cloning cosi-project/runtime @ $COSI_VER"
git clone --quiet --depth 1 --branch "$COSI_VER" \
  https://github.com/cosi-project/runtime "$WORK/cosi"

# google/rpc/status.proto is a build-time include only (NOT vendored into the
# repo). At runtime it is provided by the googleapis-common-protos package.
mkdir -p "$WORK/inc/google/rpc"
curl -fsSL \
  "https://raw.githubusercontent.com/googleapis/googleapis/master/google/rpc/status.proto" \
  -o "$WORK/inc/google/rpc/status.proto"

# --- cosi descriptors ------------------------------------------------------
# The cosi State/Resource .proto sources are no longer shipped in the runtime
# repo (only generated .pb.go). Reconstruct a FileDescriptorSet from the
# FileDescriptorProto bytes embedded in those generated files, plus the
# google/protobuf/timestamp.proto dependency, so protoc can emit Python via
# --descriptor_set_in.
cat > "$WORK/extract_cosi.py" <<'PYEOF'
import os, re, subprocess, sys, tempfile
from google.protobuf import descriptor_pb2

GO_ESC = {"a":"\a","b":"\b","f":"\f","n":"\n","r":"\r","t":"\t","v":"\v",
          "\\":"\\","'":"'",'"':'"'}

def unescape(s):
    out = bytearray(); i = 0; n = len(s)
    while i < n:
        c = s[i]
        if c != "\\":
            out.extend(c.encode("latin-1")); i += 1; continue
        i += 1; e = s[i]
        if e == "x":
            out.append(int(s[i+1:i+3], 16)); i += 3
        elif e == "u":
            out.extend(chr(int(s[i+1:i+5], 16)).encode("utf-8")); i += 5
        elif e == "U":
            out.extend(chr(int(s[i+1:i+9], 16)).encode("utf-8")); i += 9
        elif e in "01234567":
            out.append(int(s[i:i+3], 8)); i += 3
        else:
            out.extend(GO_ESC[e].encode("latin-1")); i += 1
    return bytes(out)

def extract(go_file, var):
    text = open(go_file, encoding="utf-8").read()
    rest = text[text.index(f"const {var} = ") + len(f"const {var} = "):]
    payload = bytearray(); pos = 0
    while True:
        q = rest.find('"', pos)
        if q == -1: break
        j = q + 1
        while True:
            if rest[j] == "\\": j += 2; continue
            if rest[j] == '"': break
            j += 1
        payload.extend(unescape(rest[q+1:j]))
        after = rest[j+1:rest.find("\n", j)]; pos = j + 1
        if "+" not in after: break
    return bytes(payload)

cosi_repo, grpc_inc, out_path = sys.argv[1], sys.argv[2], sys.argv[3]
v1 = os.path.join(cosi_repo, "api", "v1alpha1")
fileset = descriptor_pb2.FileDescriptorSet()

with tempfile.TemporaryDirectory() as td:
    wkt = os.path.join(td, "wkt.pb")
    subprocess.run([sys.executable, "-m", "grpc_tools.protoc", f"-I{grpc_inc}",
                    f"--descriptor_set_out={wkt}",
                    "google/protobuf/timestamp.proto"], check=True)
    s = descriptor_pb2.FileDescriptorSet(); s.ParseFromString(open(wkt,"rb").read())
    fileset.file.extend(s.file)

for name, var in (("resource", "file_v1alpha1_resource_proto_rawDesc"),
                  ("state",    "file_v1alpha1_state_proto_rawDesc")):
    raw = extract(os.path.join(v1, f"{name}.pb.go"), var)
    fdp = descriptor_pb2.FileDescriptorProto(); fdp.ParseFromString(raw)
    fileset.file.append(fdp)
    svc = [(s.name, [m.name for m in s.method]) for s in fdp.service]
    sys.stderr.write(f"   extracted {fdp.name} pkg={fdp.package} services={svc}\n")

open(out_path, "wb").write(fileset.SerializeToString())
PYEOF
echo ">> Extracting cosi State/Resource descriptors"
"$PY" "$WORK/extract_cosi.py" "$WORK/cosi" "$GRPC_INC" "$WORK/cosi.pb"

# --- protoc ----------------------------------------------------------------
GEN="$WORK/gen"; mkdir -p "$GEN"

# --python_out  -> message stubs (*_pb2.py), standard protobuf.
# --python_grpc_out -> service stubs (*_grpc.py), grpclib. Only protos that
# declare a service emit a non-empty *_grpc.py (machine.proto, state.proto);
# message-only protos (common, resource) produce empty files that are dropped
# in the flatten step below.
echo ">> protoc: Talos common + machine"
"$PY" -m grpc_tools.protoc \
  -I"$WORK/talos/api" -I"$WORK/inc" -I"$GRPC_INC" \
  --python_out="$GEN" --python_grpc_out="$GEN" \
  common/common.proto machine/machine.proto

echo ">> protoc: cosi resource + state (via descriptor set)"
"$PY" -m grpc_tools.protoc \
  --descriptor_set_in="$WORK/cosi.pb" \
  --python_out="$GEN" --python_grpc_out="$GEN" \
  v1alpha1/resource.proto v1alpha1/state.proto

# --- flatten + rewrite imports --------------------------------------------
# Both codegens emit imports rooted at each proto's package dir. protobuf's
# python_out uses `from machine import machine_pb2`; grpclib's python_grpc_out
# uses `import machine.machine_pb2` and references `machine.machine_pb2.Foo`.
# Flatten every stub into proto/ and rewrite both shapes to package-relative
# (`from . import ...`) so the package imports cleanly from anywhere on
# sys.path. Empty grpclib stubs (message-only protos: no service) are skipped.
echo ">> Flattening into $OUT_DIR and rewriting imports"
"$PY" - "$GEN" "$OUT_DIR" <<'PYEOF'
import os, re, shutil, sys
gen, out = sys.argv[1], sys.argv[2]
os.makedirs(out, exist_ok=True)

# remove previously generated stubs (keep README.md / __init__.py); covers the
# old grpcio *_pb2_grpc.py naming too, so re-running cleans up the migration.
for f in os.listdir(out):
    if f.endswith(("_pb2.py", "_pb2_grpc.py", "_grpc.py")):
        os.remove(os.path.join(out, f))

pkg_dirs = [d for d in os.listdir(gen) if os.path.isdir(os.path.join(gen, d))]
pb2_stubs, grpc_stubs = [], []
for root, _, files in os.walk(gen):
    for f in files:
        src = os.path.join(root, f)
        if f.endswith("_pb2.py"):
            shutil.copy(src, os.path.join(out, f)); pb2_stubs.append(f)
        elif f.endswith("_grpc.py"):
            # grpclib emits a _grpc.py for every proto; the ones with no service
            # contain only the header comment. Keep only the non-empty ones.
            if re.search(r'^class ', open(src, encoding="utf-8").read(), re.M):
                shutil.copy(src, os.path.join(out, f)); grpc_stubs.append(f)

pkgs = '|'.join(re.escape(d) for d in pkg_dirs)
# protobuf shape: `from <pkg> import ` -> `from . import `
pb2_rewrite = re.compile(r'^from (%s) import ' % pkgs, re.M)
# grpclib import shape: `import <pkg>.<mod>` -> `from . import <mod>`
grpc_imp = re.compile(r'^import (?:%s)\.(\w+)$' % pkgs, re.M)
# grpclib reference shape: `<pkg>.<mod>.` -> `<mod>.`
grpc_ref = re.compile(r'\b(?:%s)\.(\w+_pb2)\.' % pkgs)

for f in pb2_stubs:
    p = os.path.join(out, f)
    s = open(p, encoding="utf-8").read()
    ns = pb2_rewrite.sub('from . import ', s)
    if ns != s:
        open(p, "w", encoding="utf-8").write(ns)

for f in grpc_stubs:
    p = os.path.join(out, f)
    s = open(p, encoding="utf-8").read()
    s = grpc_imp.sub(r'from . import \1', s)
    s = grpc_ref.sub(r'\1.', s)
    open(p, "w", encoding="utf-8").write(s)

open(os.path.join(out, "__init__.py"), "a").close()
print("   stubs:", ", ".join(sorted(pb2_stubs + grpc_stubs)))
PYEOF

# Generated protobuf stubs aren't statically typed (the message classes are
# built at runtime), so tell mypy to skip them.
for f in "$OUT_DIR"/*.py; do
  if ! grep -q "mypy: ignore-errors" "$f"; then
    { printf '# mypy: ignore-errors\n'; cat "$f"; } > "$f.tmp" && mv "$f.tmp" "$f"
  fi
done

# --- verify ----------------------------------------------------------------
echo ">> Verifying imports"
PYTHONPATH="$PKG_DIR" "$PY" - <<'PYEOF'
import importlib
for m in ("proto.common_pb2", "proto.machine_pb2", "proto.machine_grpc",
          "proto.resource_pb2", "proto.state_pb2", "proto.state_grpc"):
    importlib.import_module(m)
from proto import machine_grpc, state_grpc
mm = [n for n in vars(machine_grpc.MachineServiceBase).keys()
      if not n.startswith("_")]
sm = [n for n in vars(state_grpc.StateBase).keys()
      if not n.startswith("_")]
print("   MachineService:", ", ".join(sorted(mm)))
print("   COSI State:", ", ".join(sorted(sm)))
print("   import OK")
PYEOF

echo ">> Done. Talos tag: $TALOS_TAG"
